// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwovmyhwjgeyicniehal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3b3ZteWh3amdleWljbmllaGFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNzQzODQsImV4cCI6MjA2MDc1MDM4NH0.fLvO8a4kXGfrhWlPrTgUzI8xU1ovURjo_1Pi3PHgVKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);